version: '3'

services: 
    db:
        image: postgres:13-alpine
        environment: 
            - POSTGRES_USER=superuser
            - POSTGRES_PASSWORD=supersecret
            - POSTGRES_DB=dbname
        volumes:
            - /var/lib/postgresql/data
    app:
        build:
            context: .
            target: dev
        ports:
            - 3000:3000
        volumes:
            - ./src:/app/src
            - ./keystone.ts:/app/keystone.ts
            - ./.keystone:/app/.keystone
            - ./schema.graphql:/app/schema.graphql
            - ./schema.prisma:/app/schema.prisma
